create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  customer_name text not null,
  phone text not null,
  address text not null,
  district text not null,
  size text not null,
  color text not null,
  deal text not null check (deal in ('single', 'pair')),
  total integer not null check (total > 0),
  status text not null default 'new' check (status in ('new', 'confirmed', 'packed', 'shipped', 'delivered', 'cancelled')),
  created_at timestamptz not null default now()
);

alter table public.orders enable row level security;

revoke all on table public.orders from anon, authenticated;

create index if not exists orders_created_at_idx on public.orders (created_at desc);
create index if not exists orders_status_idx on public.orders (status);
